### ISSUE TITLE
Не удается сделать нормальный pull

### ISSUE THREAD

**Issue by NikaBuk** [GOOD-Stuff/ssw_practical#17]
Создал новую ветку, в неё загрузил изменения только по task23, не удается таким образом всё равно прочитать изменения в файлах, т.к. слишком много их. Как быть?

**Comment by GOOD-Stuff** [comment]
Эх, конечно поэтому изначально и стоило делать второе задание и только потом переходить к третьему. 
Давайте тогда попробуем так: присылайте реквест как есть, я буду указывать замечания (+/- с номером строки), а там будет видно, во что это выльется.
